version: '2'

services:
    php-fpm:
        build:
            context: ./docker/php-fpm/${PHP_VERSION}
            args:
                PROJECT_NAME: ${PROJECT_NAME}
                XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY}
                XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT}
                TIME_ZONE: ${TIME_ZONE}
                PHP_FPM_PORT: ${PHP_FPM_PORT}
                IP_ADDRESS: ${IP_ADDRESS}
                USER_EMAIL: ${USER_EMAIL}
                USER_NAME: ${USER_NAME}
                XDEBUG_REMOTE_CONNECT_BACK: ${XDEBUG_REMOTE_CONNECT_BACK}
        environment:
                PHP_XDEBUG_REMOTE_HOST: ${IP_ADDRESS}
                PHP_IDE_CONFIG: serverName=${DOMAIN_NAME}
        restart: always
        ports:
            - "${SSH_PUBLIC_PORT}:22"
            - "3001:3001"
            - "3050:3050"
            - "8080:8080"
        volumes:
            - ./${PROJECT_NAME}:/var/www/${PROJECT_NAME}
            - ./logs/${PROJECT_NAME}:/var/www/${PROJECT_NAME}/var/logs
        tty: true

    nginx:
        build:
            context: ./docker/nginx
            args:
                APPLICATION_TYPE: ${APPLICATION_TYPE}
                PROJECT_NAME: ${PROJECT_NAME}
                WEBSITE_DIR: ${WEBSITE_DIR}
        restart: always
        volumes_from:
            - php-fpm
        ports:
            - "9090:80"
        volumes:
            - ./logs/nginx:/var/log/nginx
        environment:
            - VIRTUAL_HOST=${DOMAIN_NAME}
            - DOMAIN_NAME=${DOMAIN_NAME}
            - PHP_FPM_PORT=${PHP_FPM_PORT}
        links:
            - php-fpm

    mysqldb:
        build:
            context: ./docker/mysql
            args:
                CHAR_SET_SERVER: ${CHAR_SET_SERVER}
                COLLATION_SERVER: ${COLLATION_SERVER}
                DEFAULT_CHAR_SET: ${DEFAULT_CHAR_SET}
        ports:
            - "${MYSQL_PORT}:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./data/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "9091:80"
        environment:
            PMA_HOST: mysqldb
            PHP_UPLOAD_MAX_FILESIZE: 4G
            PHP_MAX_INPUT_VARS: 4G
            VIRTUAL_HOST: ${PHPMYADMIN_DOMAIN_NAME}