version: '2'

services:
    db:
        build:
            context: ./docker/mysql
            args:
                CHAR_SET_SERVER: ${CHAR_SET_SERVER}
                COLLATION_SERVER: ${COLLATION_SERVER}
                DEFAULT_CHAR_SET: ${DEFAULT_CHAR_SET}
        ports:
            - "${MYSQL_PORT}:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./data/mysql:/var/lib/mysql

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    php-fpm:
        build:
            context: ./docker/php-fpm
            args:
                PROJECT_NAME: ${PROJECT_NAME}
                XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY}
                XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT}
                TIME_ZONE: ${TIME_ZONE}
                PHP_FPM_PORT: ${PHP_FPM_PORT}
        ports:
            - "${PHP_FPM_PORT}:${PHP_FPM_PORT}"
            - "${XDEBUG_REMOTE_PORT}:${XDEBUG_REMOTE_PORT}"
            - "${SSH_PUBLIC_PORT}:22"
        volumes:
            - ./${PROJECT_NAME}:/var/www/${PROJECT_NAME}
            - ./logs/${PROJECT_NAME}:/var/www/${PROJECT_NAME}/var/logs
        links:
            - db:mysqldb
            - redis

    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    nginx:
        build:
            context: ./docker/nginx
            args:
                DOMAIN_NAME: ${DOMAIN_NAME}
                PROJECT_NAME: ${PROJECT_NAME}
                PHP_FPM_PORT: ${PHP_FPM_PORT}
                WEBSITE_DIR: ${WEBSITE_DIR}
        restart: always
        expose:
            - "80"
        links:
            - php-fpm
        volumes_from:
            - php-fpm
        volumes:
            - ./logs/nginx:/var/log/nginx
        environment:
            - VIRTUAL_HOST=${DOMAIN_NAME}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        expose:
            - "80"
        links:
            - db:mysqldb
        environment:
            - VIRTUAL_HOST=${PHPMYADMIN_DOMAIN_NAME}

    elk:
        image: willdurand/elk
        expose:
            - "80"
        volumes:
            - ./docker/elk/logstash:/etc/logstash
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php-fpm
            - nginx
        environment:
            - VIRTUAL_HOST=${ELK_DOMAIN_NAME}